SELECT nextval('person_seq');
insert into person(id, first_name, last_name, salutation) values ('1', 'Doro', 'Pesch', 'Ms');
SELECT nextval('person_seq');
insert into person(id, first_name, last_name, salutation) values ('2', 'Bobby', 'Brown', 'Mr');
SELECT nextval('person_seq');
insert into person(id, first_name, last_name, salutation) values ('3', 'Kurt', 'Cobain', 'Mr');
SELECT nextval('person_seq');
insert into person(id, first_name, last_name, salutation) values ('4', 'Nina', 'Hagen', 'Mrs');
SELECT nextval('person_seq');
insert into person(id, first_name, last_name, salutation) values ('5', 'Jimi', 'Henrix', 'Mr');
SELECT nextval('person_seq');
insert into person(id, first_name, last_name, salutation) values ('6', 'Janis', 'Joplin', 'Ms');
SELECT nextval('person_seq');
insert into person(id, first_name, last_name, salutation) values ('7', 'Joe', 'Cocker', 'Mr');
SELECT nextval('person_seq');
insert into person(id, first_name, last_name, salutation) values ('8', 'Alice', 'Cooper', 'Mr');
SELECT nextval('person_seq');
insert into person(id, first_name, last_name, salutation) values ('9', 'Bruce', 'Springsteen', 'Mr');
SELECT nextval('person_seq');
insert into person(id, first_name, last_name, salutation) values ('10', 'Eric', 'Clapton', 'Mr');